config/routes.rb
Rails.application.routes.draw do
 
 root to: 'novels#index'
 
 get 'login', to: 'sessions#new'
 post 'login', to: 'sessions#create'
 delete 'logout', to: 'sessions#destroy'
 
 get 'form', to: 'users#form'
 get 'signup', to: 'users#new'
 resources :users do
    member do
      get :relaied
      get :followings
      get :followers
      get :likes
    end
  end
 
 get 'novels/unfinished', to: 'novels#unfinished'
 get 'novels/ranking', to: 'novels#ranking'
 get 'novels/following_novels', to: 'novels#following_novels'
 get 'novels/about', to: 'novels#about'
 get 'novels/qanda', to: 'novels#qanda'
 get 'novels/guideline', to: 'novels#guideline'
 get 'novels/rule', to: 'novels#rule'
 get 'novels/privacy', to: 'novels#privacy'
 get 'novels/ranking_relay', to: 'novels#ranking_relay'
 get 'novels/following_relay', to: 'novels#following_relay'
 resources :novels do
  member do
    get :continue
    get :last
  end
  resources :comments, only: [:create, :destroy]
 end
 
 resources :relationships, only: [:create, :destroy]
 resources :favorites, only: [:create, :destroy]
 resources :notifications, only: :index
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 15 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 8, maximum: 16 },
                       format: { with: /\A(?=.*?[a-z])(?=.*?[A-Z])(?=.*?\d)[a-zA-Z\d]{8,16}+\z/ }, if: :update_password?
  validates :self_introduction, length: { maximum: 500 }
  validates :checkbox_user, presence: true

  has_many :favorites, dependent: :destroy
  has_many :already_fav, through: :favorites, source: :novel, dependent: :destroy
  has_many :novels, dependent: :destroy
  has_many :relationships, dependent: :destroy
  has_many :followings, through: :relationships, source: :follow, dependent: :destroy
  has_many :reverses_of_relationship, class_name: 'Relationship', foreign_key: 'follow_id', dependent: :destroy
  has_many :followers, through: :reverses_of_relationship, source: :user, dependent: :destroy
  
  has_many :comments, dependent: :destroy

  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end
  
  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end
  
  def following?(other_user)
    self.followings.include?(other_user)
  end
  
  def favorite(posted)
    self.favorites.find_or_create_by(novel_id: posted.id)
  end
  
  def unfavorite(posted)
    favorite = self.favorites.find_by(novel_id: posted.id)
    favorite.destroy if favorite
  end
  
  def already_fav?(posted)
    self.already_fav.include?(posted)
  end
  
  def list_fav
    Novel.where(id: self.already_fav_ids)
  end
  
  def update_password?
    password.to_s != ''
  end
  
  def create_notification_follow!(current_user)
    # temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ",current_user.id, id, 'follow'])
    # if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    # end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :edit, :update, :destroy, :form]
  before_action :still, only:[:index]
  
  def index
  end

  def show
    @user = User.find(params[:id])
    @novels = @user.novels.order(id: :desc)
    @novels_s = @novels.where(parent_id: @novels)
    counts(@user)
    counts_follow_unfollow(@user)
  end
  
  def relaied
    @user = User.find(params[:id])
    @novels = @user.novels.order(id: :desc)
    @novel_all = Novel.all
    
    counts(@user)
    counts_follow_unfollow(@user)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      log_in(@user)
      flash[:success] = 'アカウントを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'アカウントの登録に失敗しました。'
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
 
    if current_user == @user
      if @user.update(user_params)
        flash[:success] = 'プロフィールを編集しました。'
        redirect_to @user
      else
        flash.now[:danger] = 'プロフィールの編集に失敗しました。'
        render :edit
      end   
    else
        redirect_to root_url
    end
  end

  def destroy
    # @user = current_user
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = 'ユーザーを削除しました。'
    redirect_to root_url
  end
  
  def followings
    @user = User.find(params[:id])
    @followings = @user.followings.order(id: :desc)
    counts_follow_unfollow(@user)
    counts(@user)
  end
  
  def followers
    @user = User.find(params[:id])
    @followers = @user.followers.order(id: :desc)
    counts_follow_unfollow(@user)
    counts(@user)
  end
  
  def likes
    @user = User.find(params[:id])
    # @novels = @user.list_fav.order(id: :asc).page(params[:page])
    @novels = @user.favorites.order(created_at: "DESC").map{|favorite| favorite.novel}
    counts_follow_unfollow(@user)
    counts(@user)
  end
  
  def form
  end
  
  helper_method :nextcount

  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :self_introduction, :twitter, :checkbox_user)
  end
  
  def counts(user)
    @user_novel_all = user.novels
    @s = []
    @r = []
    
    @user_novel_all.each do |user_novel|
      if user_novel.id == user_novel.parent_id
        @s.push(user_novel)
      else
        @r.push(user_novel)
      end
    end
    @count_novels_self = @s.count
    @count_novels_relay = @r.count
  end
  
  def nextcount(novel)
    @nextnovels = Novel.where(parent_id: novel.id).where('id != ? ', novel.id )
    @nextcount = @nextnovels.count
    
    return @nextcount
  end
  
end

app/views/users/followers.html.erb
<div class="row">
  <aside class="col-lg-3">
    <div class="sample_box_title"><p><%= @user.name %></p></div>
    <div class="sample_box3_2">
      <p class="pre-wrap"><%= @user.self_introduction %></p>
      <% if @user == current_user %>
        <a href="<%= notifications_path %>" class="btn-animation-02 mb-2 show-notice"><span class="btn-span"><i class="fas fa-bell mr-2"></i>通知
          <% if unchecked_notifications.any? %>
            <i class="fa fa-circle" style="color: gold;"></i>
          <% end %>
        </span></a>
      <% end %>
      <% if @user.twitter.present? %>
        <a href="https://twitter.com/<%= @user.twitter %>" target="blank" class="btn-animation-02 mb-2 show-twitter"><span class="btn-span"><i class="fab fa-twitter mr-2"></i>Twitter</span></a>
      <% end %>
      <% if current_user == @user %>
        <a href="<%= edit_user_path %>" class="btn-animation-02"><span class="btn-span">プロフィールを編集</span></a>
      <% end %>
    </div>
    <%= render 'relationships/follow_button', user: @user %>
  </aside>
  <div class="col-lg-9">
    <a href="<%= user_path(@user) %>" class="btn-flat-vertical-border <%= 'active-show' if current_page?(user_path(@user)) %>">オリジナル  <span class="badge badge-secondary"><%= @count_novels_self %></span></a>
    <a href="<%= relaied_user_path(@user) %>" class="btn-flat-vertical-border <%= 'active-show' if current_page?(relaied_user_path(@user)) %>">リレー  <span class="badge badge-secondary"><%= @count_novels_relay %></span></a>
    <a href="<%= followings_user_path(@user) %>" class="btn-flat-vertical-border <%= 'active-show' if current_page?(followings_user_path(@user)) %>">フォロー  <span class="badge badge-secondary"><%= @count_followings %></span></a>
    <a href="<%= followers_user_path(@user) %>" class="btn-flat-vertical-border <%= 'active-show' if current_page?(followers_user_path(@user)) %>">フォロワー  <span class="badge badge-secondary"><%= @count_followers %></span></a>
    <a href="<%= likes_user_path %>" class="btn-flat-vertical-border <%= 'active-show' if current_page?(likes_user_path) %>">いいね　<span class="badge badge-secondary"><%= @count_favorites %></span></a>
    <%= render 'users', users: @followers %>
    <% unless @followers.present? %>
      <div class="box8 mb-0">
        <div class="cautionbox-title"><i class="fas fa-exclamation-triangle icon"></i>Attention</div>
        <p class="nothing">フォロワーはいません。</p>
        <div class="balloon5">
          <div class="faceicon">
            <img src="<%= asset_path "pen.jpg" %>" class="ml-4">
          </div>
          <div class="question">
            <div class="chatting">
              <div class="says mr-5">
                <p style="font-weight:bold; font-size:16px;">たくさん<a href="<%= new_novel_path %>">ストーリーを投稿</a>して注目を集めよう！</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/followings.html.erb
<div class="row">
  <aside class="col-lg-3">
    <div class="sample_box_title"><p><%= @user.name %></p></div>
    <div class="sample_box3_2">
      <p class="pre-wrap"><%= @user.self_introduction %></p>
      <% if @user == current_user %>
        <a href="<%= notifications_path %>" class="btn-animation-02 mb-2 show-notice"><span class="btn-span"><i class="fas fa-bell mr-2"></i>通知
          <% if unchecked_notifications.any? %>
            <i class="fa fa-circle" style="color: gold;"></i>
          <% end %>
        </span></a>
      <% end %>
      <% if @user.twitter.present? %>
        <a href="https://twitter.com/<%= @user.twitter %>" target="blank" class="btn-animation-02 mb-2 show-twitter"><span class="btn-span"><i class="fab fa-twitter mr-2"></i>Twitter</span></a>
      <% end %>
      <% if current_user == @user %>
        <a href="<%= edit_user_path %>" class="btn-animation-02"><span class="btn-span">プロフィールを編集</span></a>
      <% end %>
    </div>
    <%= render 'relationships/follow_button', user: @user %>
  </aside>
  <div class="col-lg-9">
    <a href="<%= user_path(@user) %>" class="btn-flat-vertical-border <%= 'active-show' if current_page?(user_path(@user)) %>">オリジナル  <span class="badge badge-secondary"><%= @count_novels_self %></span></a>
    <a href="<%= relaied_user_path(@user) %>" class="btn-flat-vertical-border <%= 'active-show' if current_page?(relaied_user_path(@user)) %>">リレー  <span class="badge badge-secondary"><%= @count_novels_relay %></span></a>
    <a href="<%= followings_user_path(@user) %>" class="btn-flat-vertical-border <%= 'active-show' if current_page?(followings_user_path(@user)) %>">フォロー  <span class="badge badge-secondary"><%= @count_followings %></span></a>
    <a href="<%= followers_user_path(@user) %>" class="btn-flat-vertical-border <%= 'active-show' if current_page?(followers_user_path(@user)) %>">フォロワー  <span class="badge badge-secondary"><%= @count_followers %></span></a>
    <a href="<%= likes_user_path %>" class="btn-flat-vertical-border <%= 'active-show' if current_page?(likes_user_path) %>">いいね　<span class="badge badge-secondary"><%= @count_favorites %></span></a>
    <%= render 'users', users: @followings %>
    <% unless @followings.present? %>
      <div class="box8 mb-0">
        <div class="cautionbox-title"><i class="fas fa-exclamation-triangle icon"></i>Attention</div>
        <p class="nothing">フォローしているユーザーはいません。</p>
        <div class="balloon5">
          <div class="faceicon">
            <img src="<%= asset_path "pen.jpg" %>" class="ml-4">
          </div>
          <div class="question">
            <div class="chatting">
              <div class="says mr-5">
                <p style="font-weight:bold; font-size:16px;"><a href="<%= root_path %>">完結済みストーリー</a>や<a href="<%= novels_ranking_path %>">いいねランキング</a>から気になるユーザーをフォローしよう！</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/form.html.erb
<div class="text-center" style="width:100%;">
  <h3 class="ribbon1">お問い合わせ</h3>
</div>

<div class="container">
  <div class="row">
    <div class="col-12 balloon5 text-center">
      <div class="faceicon">
        <img src="<%= asset_path "tori.jpg" %>" class="ml-5">
      </div>
      <div class="chatting">
        <div class="says mr-5" style="margin-left:150px;">
          <p style="font-weight:bold; font-size:16px;">RelayNovelは、現在も開発中です。ご不明な点などございましたら、このフォームからお気軽にご質問お願いします！<br>ご記入いただいた内容はGoogleフォームにて管理しています<br>ご記入いただいたメールアドレス宛に返信させていただくことがあります</p>
        </div>
      </div>
    </div>
  </div>
</div>
    
<div class="container">
  <div class="row">
    <div class="side col-lg-3">
      <h2 style="color: #494949;">RelayNovelについて</h2>
      <a href="<%= novels_about_path %>" class="mb-1 display index-search <%= 'active-tag' if current_page?(novels_about_path) %>"><i class="fas fa-desktop icon"></i>サイト紹介</a>
      <a href="<%= novels_qanda_path %>" class="mb-1 display index-search <%= 'active-tag' if current_page?(novels_qanda_path) %>"><i class="far fa-comments icon"></i>Q & A</a>
      <% if current_user.present? %>
        <a href="<%= form_path %>" class="mb-1 display index-search <%= 'active-tag' if current_page?(form_path) %>"><i class="far fa-envelope icon"></i>お問い合わせ</a>
      <% end %>
      <h2 style="color: #494949;">ストーリーを探す</h2>
      <a href="<%= root_path %>" class="mb-1 display index-search <%= 'active-tag' if current_page?(root_path) %>"><i class="fas fa-dove icon"></i>完結済みストーリー</a>
      <a href="<%= novels_unfinished_path %>" class="display index-search <%= 'active-tag' if current_page?(novels_unfinished_path) %>"><i class="fas fa-egg icon"></i>未完ストーリー</a>
      <a href="<%= novels_ranking_path %>" class="mt-1 display index-search <%= 'active-tag' if current_page?(novels_ranking_path) %>"><i class="fas fa-crown icon"></i>いいねランキング</a>
      <% if current_user.present? %>
        <a href="<%= novels_following_novels_path %>" class="mt-1 display index-search <%= 'active-tag' if current_page?(novels_following_novels_path) %> <%= 'active-tag' if current_page?(novels_following_relay_path) %>"><i class="fas fa-user-friends icon"></i>タイムライン</a>
      <% end %>
    </div>

    
    <div class="side col-lg-9">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <iframe src="https://docs.google.com/forms/d/e/1FAIpQLSckHbbDZpZXgxuJR8I3Gi1hQNCA74peWDpW9gsbAR4x7bJB0A/viewform?embedded=true" width=100% height="1303" frameborder="0" marginheight="0" marginwidth="0">読み込んでいます…</iframe>
          </div>
        </div>
      </div>
    </div>
    
  </div>
</div>

app/views/users/likes.html.erb
<div class="row">
  <aside class="col-lg-3">
    <div class="sample_box_title"><p><%= @user.name %></p></div>
    <div class="sample_box3_2">
      <p class="pre-wrap"><%= @user.self_introduction %></p>
      <% if @user == current_user %>
        <a href="<%= notifications_path %>" class="btn-animation-02 mb-2 show-notice"><span class="btn-span"><i class="fas fa-bell mr-2"></i>通知
          <% if unchecked_notifications.any? %>
            <i class="fa fa-circle" style="color: gold;"></i>
          <% end %>
        </span></a>
      <% end %>
      <% if @user.twitter.present? %>
        <a href="https://twitter.com/<%= @user.twitter %>" target="blank" class="btn-animation-02 mb-2 show-twitter"><span class="btn-span"><i class="fab fa-twitter mr-2"></i>Twitter</span></a>
      <% end %>
      <% if current_user == @user %>
        <a href="<%= edit_user_path %>" class="btn-animation-02"><span class="btn-span">プロフィールを編集</span></a>
      <% end %>
    </div>
    <%= render 'relationships/follow_button', user: @user %>
  </aside>
  <div class="col-lg-9">
    <a href="<%= user_path(@user) %>" class="btn-flat-vertical-border <%= 'active-show' if current_page?(user_path(@user)) %>">オリジナル  <span class="badge badge-secondary"><%= @count_novels_self %></span></a>
    <a href="<%= relaied_user_path(@user) %>" class="btn-flat-vertical-border <%= 'active-show' if current_page?(relaied_user_path(@user)) %>">リレー  <span class="badge badge-secondary"><%= @count_novels_relay %></span></a>
    <a href="<%= followings_user_path(@user) %>" class="btn-flat-vertical-border <%= 'active-show' if current_page?(followings_user_path(@user)) %>">フォロー  <span class="badge badge-secondary"><%= @count_followings %></span></a>
    <a href="<%= followers_user_path(@user) %>" class="btn-flat-vertical-border <%= 'active-show' if current_page?(followers_user_path(@user)) %>">フォロワー  <span class="badge badge-secondary"><%= @count_followers %></span></a>
    <a href="<%= likes_user_path %>" class="btn-flat-vertical-border <%= 'active-show' if current_page?(likes_user_path) %>">いいね　<span class="badge badge-secondary"><%= @count_favorites %></span></a>
    <%= render 'novels/liked', novels: @novels %>
    <% unless @novels.present? %>
      <div class="box8 mb-0">
        <div class="cautionbox-title"><i class="fas fa-exclamation-triangle icon"></i>Attention</div>
        <p class="nothing">いいねしているストーリーはありません。</p>
        <div class="balloon5">
          <div class="faceicon">
            <img src="<%= asset_path "pen.jpg" %>" class="ml-4">
          </div>
          <div class="question">
            <div class="chatting">
              <div class="says mr-5">
                <p style="font-weight:bold; font-size:16px;"><a href="<%= novels_ranking_relay_path %>">いいねランキング</a>や<a href="<%= root_path %>">完結済みストーリー</a>からお気に入りのストーリーを探そう！</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="text-center login-account">
  <h1 class="mb-0">アカウント登録フォーム</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">
    
    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
    
      <div class="form-group">
        <%= f.label :name, 'お名前', class:'form-color' %><span class="ml-1 attention">*</span>
        <%= f.text_field :name, class: 'form-control', placeholder: '最大15文字まで入力できます' %>
      </div>
    
       <div class="form-group">
        <%= f.label :email, 'メールアドレス', class:'form-color' %><span class="ml-1 attention">*</span>
        <%= f.text_field :email, class: 'form-control', placeholder: 'ログインに使用するアドレスを入力してください' %>
      </div>
      
      <div class="form-group">
        <%= f.label :password, 'パスワード', class:'form-color' %><span class="ml-1 attention">*</span>
        <%= f.password_field :password, class: 'form-control', placeholder: '半角大小英・数字を組み合わせて8～16文字の間で作成してください' %>
      </div>
      
      <div class="form-group">
        <%= f.label :password_confirmation, '確認用パスワード', class:'form-color' %><span class="ml-1 attention">*</span>
        <%= f.password_field :password_confirmation, class: 'form-control', placeholder: 'パスワードをもう一度入力してください' %>
      </div>
      
      <div class="text-center mb-3">
        <p class="mb-1"><a href="<%= novels_rule_path %>" target="_blank" rel="noopener noreferrer">利用規約</a>と<a href="<%= novels_guideline_path %>" target="_blank" rel="noopener noreferrer">ガイドライン</a>を必ずご確認ください。</p>
        <%= f.check_box :checkbox_user, :as => :boolean, checked:false %>
        <%= f.label :利用規約に同意する %>
      </div>
      <%= f.submit 'アカウント登録', class: 'btn login-account-btn', style:'font-weight:bold;' %>
    <% end %>
  </div>
</div>

<div class="text-center">
  <p class="mt-3">すでにアカウントをお持ちの方は<%= link_to 'こちらからログイン', login_path %></p>
</div>

app/views/users/relaied.html.erb
<div class="row">
  <aside class="col-lg-3">
    <div class="sample_box_title"><p><%= @user.name %></p></div>
    <div class="sample_box3_2">
      <p class="pre-wrap"><%= @user.self_introduction %></p>
      <% if @user == current_user %>
        <a href="<%= notifications_path %>" class="btn-animation-02 mb-2 show-notice"><span class="btn-span"><i class="fas fa-bell mr-2"></i>通知
          <% if unchecked_notifications.any? %>
            <i class="fa fa-circle" style="color: gold;"></i>
          <% end %>
        </span></a>
      <% end %>
      <% if @user.twitter.present? %>
        <a href="https://twitter.com/<%= @user.twitter %>" target="blank" class="btn-animation-02 mb-2 show-twitter"><span class="btn-span"><i class="fab fa-twitter mr-2"></i>Twitter</span></a>
      <% end %>
      <% if current_user == @user %>
        <a href="<%= edit_user_path %>" class="btn-animation-02"><span class="btn-span">プロフィールを編集</span></a>
      <% end %>
    </div>
    <%= render 'relationships/follow_button', user: @user %>
  </aside>
  <div class="col-lg-9">
    <a href="<%= user_path(@user) %>" class="btn-flat-vertical-border <%= 'active-show' if current_page?(user_path(@user)) %>">オリジナル  <span class="badge badge-secondary"><%= @count_novels_self %></span></a>
    <a href="<%= relaied_user_path(@user) %>" class="btn-flat-vertical-border <%= 'active-show' if current_page?(relaied_user_path(@user)) %>">リレー  <span class="badge badge-secondary"><%= @count_novels_relay %></span></a>
    <a href="<%= followings_user_path(@user) %>" class="btn-flat-vertical-border <%= 'active-show' if current_page?(followings_user_path(@user)) %>">フォロー  <span class="badge badge-secondary"><%= @count_followings %></span></a>
    <a href="<%= followers_user_path(@user) %>" class="btn-flat-vertical-border <%= 'active-show' if current_page?(followers_user_path(@user)) %>">フォロワー  <span class="badge badge-secondary"><%= @count_followers %></span></a>
    <a href="<%= likes_user_path %>" class="btn-flat-vertical-border <%= 'active-show' if current_page?(likes_user_path) %>">いいね　<span class="badge badge-secondary"><%= @count_favorites %></span></a>
    <%= render 'novels/relaied_novels', novels: @novels, novel_all: @novel_all %>
    <% if @count_novels_relay == 0 %>
      <div class="box8 mb-0">
        <div class="cautionbox-title"><i class="fas fa-exclamation-triangle icon"></i>Attention</div>
        <p class="nothing">投稿しているリレーストーリーがありません。</p>
        <div class="balloon5">
          <div class="faceicon">
            <img src="<%= asset_path "pen.jpg" %>" class="ml-4">
          </div>
          <div class="question">
            <div class="chatting">
              <div class="says mr-5">
                <p style="font-weight:bold; font-size:16px;"><a href="<%= novels_unfinished_path %>">未完ストーリー</a>から続きを書いてみたいストーリーを探そう！</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <aside class="col-lg-3">
      <div class="sample_box_title">
        <p><%= @user.name %></p>
      </div>
      <div class="sample_box3_2">
        <p class="pre-wrap" style="color:gray;"><%= @user.self_introduction %></p>
        <% if @user == current_user %>
          <a href="<%= notifications_path %>" class="btn-animation-02 mb-2 show-notice"><span class="btn-span"><i class="fas fa-bell mr-2"></i>通知
            <% if unchecked_notifications.any? %>
              <i class="fa fa-circle" style="color: gold;"></i>
            <% end %>
          </span></a>
        <% end %>
        <% if @user.twitter.present? %>
          <a href="https://twitter.com/<%= @user.twitter %>" target="blank" class="btn-animation-02 mb-2 show-twitter"><span class="btn-span"><i class="fab fa-twitter mr-2"></i>Twitter</span></a>
        <% end %>
        <% if current_user == @user %>
          <a href="<%= edit_user_path %>" class="btn-animation-02"><span class="btn-span">プロフィールを編集</span></a>
        <% end %>
      </div>
      <%= render 'relationships/follow_button', user: @user %>
    </aside>
    <div class="col-lg-9" class="pt-2">
      <a href="<%= user_path(@user) %>" class="btn-flat-vertical-border <%= 'active-show' if current_page?(user_path(@user)) %>">オリジナル  <span class="badge badge-secondary"><%= @count_novels_self %></span></a>
      <a href="<%= relaied_user_path(@user) %>" class="btn-flat-vertical-border <%= 'active-show' if current_page?(relaied_user_path(@user)) %>">リレー  <span class="badge badge-secondary"><%= @count_novels_relay %></span></a>
      <a href="<%= followings_user_path(@user) %>" class="btn-flat-vertical-border <%= 'active-show' if current_page?(followings_user_path(@user)) %>">フォロー  <span class="badge badge-secondary"><%= @count_followings %></span></a>
      <a href="<%= followers_user_path(@user) %>" class="btn-flat-vertical-border <%= 'active-show' if current_page?(followers_user_path(@user)) %>">フォロワー  <span class="badge badge-secondary"><%= @count_followers %></span></a>
      <a href="<%= likes_user_path %>" class="btn-flat-vertical-border <%= 'active-show' if current_page?(likes_user_path) %>">いいね　<span class="badge badge-secondary"><%= @count_favorites %></span></a>
      <%= render 'novels/novels', novels: @novels_s %>
      <% unless @novels_s.present? %>
        <div class="box8 mb-0">
          <div class="cautionbox-title"><i class="fas fa-exclamation-triangle icon"></i>Attention</div>
          <p class="nothing">投稿しているオリジナルストーリーがありません。</p>
          <div class="balloon5">
            <div class="faceicon">
              <img src="<%= asset_path "pen.jpg" %>" class="ml-4">
            </div>
            <div class="question">
              <div class="chatting">
                <div class="says mr-5">
                  <p style="font-weight:bold; font-size:16px;"><a href="<%= new_novel_path %>">ストーリーを投稿</a>してみよう！</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>