config/routes.rb
Rails.application.routes.draw do
 
 root to: 'novels#index'
 
 get 'login', to: 'sessions#new'
 post 'login', to: 'sessions#create'
 delete 'logout', to: 'sessions#destroy'
 
 get 'form', to: 'users#form'
 get 'signup', to: 'users#new'
 resources :users do
    member do
      get :relaied
      get :followings
      get :followers
      get :likes
    end
  end
 
 get 'novels/unfinished', to: 'novels#unfinished'
 get 'novels/ranking', to: 'novels#ranking'
 get 'novels/following_novels', to: 'novels#following_novels'
 get 'novels/about', to: 'novels#about'
 get 'novels/qanda', to: 'novels#qanda'
 get 'novels/guideline', to: 'novels#guideline'
 get 'novels/rule', to: 'novels#rule'
 get 'novels/privacy', to: 'novels#privacy'
 get 'novels/ranking_relay', to: 'novels#ranking_relay'
 get 'novels/following_relay', to: 'novels#following_relay'
 resources :novels do
  member do
    get :continue
    get :last
  end
  resources :comments, only: [:create, :destroy]
 end
 
 resources :relationships, only: [:create, :destroy]
 resources :favorites, only: [:create, :destroy]
 resources :notifications, only: :index
end

app/models/novel.rb
class Novel < ApplicationRecord
  is_impressionable
  
  belongs_to :user
  
  has_many :favorites, dependent: :destroy
  has_many :fav_user, through: :favorites, source: :user, dependent: :destroy
  
  has_many :comments, dependent: :destroy
  
  has_many :notifications, dependent: :destroy
  
  validates :title, presence: true, length: { maximum: 50 }
  validates :outline, presence: true, length: { maximum: 1000 }
  validates :content, presence: true, length: { minimum: 50, maximum: 20000}
  validates :fin, presence: true
  
  def create_notification_like!(current_user)
    # すでに「いいね」されているか検索
    temp = Notification.where(["visitor_id = ? and visited_id = ? and novel_id = ? and action = ? ", current_user.id, user_id, id, 'like'])
    # いいねされていない場合のみ、通知レコードを作成
    if temp.blank?
      notification = current_user.active_notifications.new(
        novel_id: id,
        visited_id: user_id,
        action: 'like'
      )
      # 自分の投稿に対するいいねの場合は、通知済みとする
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end
  
  
  def create_notification_comment!(current_user, comment_id)
    # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
    # temp_ids = Comment.select(:user_id).where(novel_id: id).where.not(user_id: current_user.id).distinct
    # temp_ids.each do |temp_id|
    #   save_notification_comment!(current_user, comment_id, temp_id['user_id'])
    # end
    # まだ誰もコメントしていない場合は、投稿者に通知を送る
    save_notification_comment!(current_user, comment_id, user_id)
    # if temp_ids.blank?
  end

  def save_notification_comment!(current_user, comment_id, visited_id)
    # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
    notification = current_user.active_notifications.new(
      novel_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    # 自分の投稿に対するコメントの場合は、通知済みとする
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end
  
  def create_notification_story!(current_user)
    # # すでに「続編作成」されているか検索
    # temp_s = Notification.where(["visitor_id = ? and visited_id = ? and novel_id = ? and action = ? ", current_user.id, user_id, id, 'story'])
    # # いいねされていない場合のみ、通知レコードを作成
    # if temp_s.blank?
      notification = current_user.active_notifications.new(
        novel_id: id,
        visited_id: user_id,
        action: 'story'
      )
      # 自分の投稿に対する続編作成の場合は、通知済みとする
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
  end

end

app/controllers/novels_controller.rb
class NovelsController < ApplicationController
  before_action :require_user_logged_in, only: [:new, :create, :continue, :last, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update,:destroy]
  before_action :story_end_check, only: [:last]
  before_action :story_continue_check, only: [:continue]
  before_action :before_destroy, only:[:destroy]
  before_action :before_destroy_check, only:[:destroy]
  before_action :before_index, only:[:index]
  # 未実装
  before_action :still, only:[:edit, :update]  
  
  impressionist :actions=> [:show]


  
  def index
    @novels = Novel.all.order(id: "DESC")
  end
  
  def unfinished
    @novels = Novel.all.order(id: "DESC")
    @novels.each do |novel|
    end
  end
  
  def ranking
    @ranking = Novel.find(Favorite.group(:novel_id).order('count(novel_id) desc').pluck(:novel_id))
    @order = 0
  end
  
  def ranking_relay
    @ranking = Novel.find(Favorite.group(:novel_id).order('count(novel_id) desc').pluck(:novel_id))
    
    @order = 0
  end
  
  def following_novels
    @user = current_user
    @users = @user.followings
    @novels = Novel.all
    @follow_novel = @novels.where(user_id: @users)
    @f = @follow_novel.where(parent_id: @follow_novel)
    @novels = []
    if @users.present?
      @users.each do |user|
        user_novels = Novel.where(user_id: user.id).order(created_at: :desc)
        @novels.concat(user_novels)
      end
      @timeline = @novels.sort_by{|novel| novel.created_at}.reverse
        if @novels.nil?
          flash[:notice]="まだ投稿がありません…"
          redirect_to("/")
        end
    end
  end
  
  def following_relay
    @user  = current_user
    @users = @user.followings
    @novels = Novel.all
    @follow_novel = @novels.where(user_id: @users)
    @f = @follow_novel.where.not(parent_id: @follow_novel)
    @novels = []
    if @users.present?
      @users.each do |user|
        user_novels = Novel.where(user_id: user.id).order(created_at: :desc)
        @novels.concat(user_novels)
      end
      @timeline = @novels.sort_by{|novel| novel.created_at}.reverse
        if @novels.nil?
          flash[:notice]="まだ投稿がありません…"
          redirect_to("/")
        end
    end
  end

  def show
    @novel = Novel.find(params[:id])
    @next_novels = Novel.where(parent_id: @novel.id).where('id > ?', @novel.id)
    if @novel.fin != 3
      @parent_novel = Novel.find_by(id: @novel.parent_id)
      @grandparent_novel = Novel.find_by(id: @novel.grandparent_id)
    end
    @url = request.url
    
    # @comments = @novel.comments
    @comment = Comment.new
    
    impressionist(@novel, nil)
    
  end

  def new
    @novel = Novel.new
  end
  
  def continue
    @novel = Novel.find(params[:id])
  end
  
  def last
    @novel = Novel.find(params[:id])
  end

  def create
    @novel = current_user.novels.build(novel_params)
    if @novel.save
      parent_info
      grandparent_info
      fin_info
      
      novel = Novel.find_by(id: @novel.parent_id)
      
      novel.create_notification_story!(current_user)
      
      flash[:success] = 'ストーリーを投稿しました。'
      redirect_to novel_path(@novel)
    else
      @novels = current_user.novels.order(id: :desc).page(params[:page])
      flash[:danger] = 'ストーリーの投稿に失敗しました。'
      redirect_back(fallback_location: root_path)
    end
  end

  def edit
  end

  def update
  end

  def destroy
    @novel.destroy
    flash[:success] = 'ストーリーを削除しました。'
    redirect_to user_path(current_user)
  end
  
  def about
  end
  
  def qanda
  end
  
  def guideline
  end
  
  def rule
  end
  
  def privacy
  end
  
  
  helper_method :next_next
  helper_method :nextcount
  
  private
  
  def next_next(sequel)
    @a = Novel.find_by(id: sequel.id)
    @b = Novel.where(parent_id: @a.id)
    if @b.present?
      return 'さらにリレーが続けられています'
    else
      return '続きのストーリーは投稿されていません'
    end
  end
  
  def novel_params
    params.require(:novel).permit(:title, :outline, :content, :parent_id, :grandparent_id, :fin, :user_id)
  end
  
  def parent_info
    if @novel.parent_id == nil
      @novel.parent_id = @novel.id
      @novel.save
    end
  end
  
  def grandparent_info
    if @novel.grandparent_id == nil
      @novel.grandparent_id = @novel.id
      @novel.save
    end
  end
  
  def fin_info
    @grand_novel = Novel.find_by(id: @novel.grandparent_id)
    if @novel.fin == 1 && @grand_novel.fin == 0
      @grand_novel.fin = 1
      @grand_novel.save
    end
  end
  
  def correct_user
    @novel = current_user.novels.find_by(id: params[:id])
    unless @novel
      redirect_to login_path
    end
  end
  
  def story_continue_check
    @novel = Novel.find(params[:id])
    unless @novel.parent_id == @novel.grandparent_id
      redirect_to @novel
    end
  end
  
  def story_end_check
    @novel = Novel.find(params[:id])
    unless @novel.parent_id != @novel.grandparent_id
      redirect_to @novel
    end
  end
  
  def before_destroy
    @children = Novel.where(parent_id: @novel.id)
    @children.each do |child|
      child.fin = 3
      child.save
    end
  end
    
  def before_destroy_check
    @g = Novel.find_by(id: @novel.grandparent_id)
    if @g.present?
      @g.fin = 0
      @g.save
    end
  end 
  
  def before_index
    @grands = Novel.where(fin: 0)
    @grands.each do |grand|
      if grand.id == grand.parent_id && grand.fin == 0
        @end = Novel.where(grandparent_id: grand.id).where(fin: 1)
        if @end
          @end.each do |ketsu|
            @third = Novel.where(id: ketsu.parent_id).where(fin: 0)
            if @third
              grand.fin = 1
              grand.save
            end
          end
        end
      end
    end
  end
  
  def nextcount(novel)
    @nextnovels = Novel.where(parent_id: novel.id).where('id != ? ', novel.id )
    @nextcount = @nextnovels.count
    
    return @nextcount
  end
  
  
end

app/views/novels/edit.html.erb
<h1>Novels#edit</h1>
<p>Find me in app/views/novels/edit.html.erb</p>

app/views/novels/guideline.html.erb
<div style="color: #494949;">
<h1 class="rule" style="margin-bottom:40px; font-size:35px;">RelayNovelガイドライン</h1>

<h1 class="rule">投稿について</h1>
<p>
投稿された作品に対して、運営側が手を加えることは一切ありません。
他サービスで公開されている作品についても「RelayNovel」に投稿することができます。ただし、他サービスの規約等で制限がある場合があるのでご注意ください。
RelayNovelに投稿できる作品は会員自らが創作した作品に限ります。
</p>

<h1 class="rule">「RelayNovel」上での表現について</h1>
<p>
表現の自由を制限するものではありませんが、青少年を含む利用者が気持ちよく利用できるように以下の表現についてはそれ自体が作品の目的（テーマ）ではなく、物語上の必要な要素として必要最低限の描写となるよう配慮をお願いいたします。
</p>
<ul style="padding-left:20px;">
  <li class="lista">表現・描写などにより著しく性欲を刺激するもの</li>
  <li class="lista">暴力的又は陰惨な画像・表現・描写などにより興味本位に暴力行為又は残虐性を喚起・助長するもの</li>
  <li class="lista">自殺を誘発・助長・ほう助するもの</li>
  <li class="lista">犯罪行為及び刑罰法令に抵触する行為又は誘引・助長・ほう助するもの</li>
  <li class="lista">他者に対する差別表現、権利を侵害する行為</li>
</ul>
<p>
上記についての過剰な表現や、表現・描写の割合が大きいものについては、作品の非公開化・削除を行う場合があります。
</p>
「18歳の飲酒・喫煙」など、法律で禁止されている行為について、物語の表現上やむをえず描写する場合は、そういった描写のある作品の末尾に『この物語は、法律・法令に反する行為を容認・推奨するものではありません』など、行為の非推奨コメントを記載してください。
</p>

<h1 class="rule">投稿された作品の商用等の利用に関して</h1>
<p>
出版権を投稿者ご自身が保持して、同人誌販売(即売会・同人誌流通)・電子出版を行なうにあたって、RelayNovel上で販売に関する告知・宣伝を実施することは、利用規約第12条（営利目的利用の禁止）に抵触する行為となります。
</p>

<h1 class="rule">レビューについて</h1>
<p>
「作者への誹謗中傷」、「作品と関係ない内容」、「誤字脱字の指摘」などの内容や、「作品を読まずに投稿した行為」、また「RelayNovelのサイト内外を問わず、レビューを強要する行為」と判断した投稿は削除する場合があります。また利用規約に違反する内容や、作者への誹謗中傷などの投稿を行ったと運営が判断した場合は、利用停止やアカウント削除の対応を行う場合があります。
</p>

<h1 class="rule">アカウントに関して</h1>
<p>
本サイト管理者が認める場合を除き、一人で複数のアカウントを作成し、利用することは禁止します。
</p>

<p style="border-top:1px solid gray; padding-top:10px; margin-top:30px;">更新日　　2020年7月22日作成</p>
</div>

app/views/novels/index.html.erb
<div class="toppage-box">
  <img src="<%= asset_path "1.jpg" %>" style="width:100%;">
  <div class="top-exp" style="height:100%">
    <h1 class="text-center mt-3">RelayNovel</h1>
    <p class="text-center" style="font-weight:bold;">イチから無限のストーリーが生まれる場所</p>
    <% unless current_user.present? %>
      <a href="novels/new" class="btn mt-0 mb-3">
        <p>アカウント登録 / ログインして</p>
        <p class="button-font">ストーリーを書く</p>
      </a>
    <% end %>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="side col-md-3">
      <h2 style="color: #494949">RelayNovelについて</h2>
      <a href="<%= novels_about_path %>" class="mb-1 display index-search <%= 'active-tag' if current_page?(novels_about_path) %>"><i class="fas fa-desktop icon"></i>サイト紹介</a>
      <a href="<%= novels_qanda_path %>" class="mb-1 display index-search <%= 'active-tag' if current_page?(novels_qanda_path) %>"><i class="far fa-comments icon"></i>Q & A</a>
      <% if current_user.present? %>
        <a href="<%= form_path %>" class="mb-1 display index-search <%= 'active-tag' if current_page?(form_path) %>"><i class="far fa-envelope icon"></i>お問い合わせ</a>
      <% end %>
      <h2 style="color: #494949">ストーリーを探す</h2>
      <a href="<%= root_path %>" class="mb-1 display index-search <%= 'active-tag' if current_page?(root_path) %>"><i class="fas fa-dove icon"></i>完結済みストーリー</a>
      <a href="<%= novels_unfinished_path %>" class="display index-search <%= 'active-tag' if current_page?(novels_unfinished_path) %>"><i class="fas fa-egg icon"></i>未完ストーリー</a>
      <a href="/novels/ranking" class="mt-1 display index-search <%= 'active-tag' if current_page?(novels_ranking_path) %> <%= 'active-tag' if current_page?(novels_ranking_relay_path) %>"><i class="fas fa-crown icon"></i>いいねランキング</a>
      <% if current_user.present? %>
        <a href="<%= novels_following_novels_path %>" class="mt-1 display index-search <%= 'active-tag' if current_page?(novels_following_novels_path) %> <%= 'active-tag' if current_page?(novels_following_relay_path) %>"><i class="fas fa-user-friends icon"></i>タイムライン</a>
      <% end %>
    </div>
  
    <div class="col-md-9">
      <h2 class="toppage-title mb-0" style="color: #494949"><i class="fas fa-dove icon mr-2 pt-2" style="color: #9ACCFF; font-size:30px;"></i>完結しているストーリー</h2>
      <% @novels.each do |novel| %>
        <% rand = Rails.env.production? ? "RANDOM()" : "rand()" %>
        <% @comments = novel.comments.order(rand).limit(1) %>
        <% if novel.parent_id == novel.grandparent_id && novel.fin == 1 %>
          <a href="<%= novel_path(novel) %>" class="linkbox">
            <div class="novel-border media-body show">
              <p class='font-weight-bold pre-wrap font mr-3' style='font-size:20px;'><%= novel.outline.truncate(100) %></p>
              <div class="form-color">
                <p class="display title" style="color: #494949;">『<%= novel.title %>』</p>
                <object><p class="display" style="color: #494949;">著者：<%= link_to novel.user.name, user_path(novel.user), class:'text-reset' %></p></object>
                <div class="pv-fav-foot-time mt-2">
                  <p class=" icon-float mr-2"><i class="fas fa-shoe-prints icon"></i><%=  novel.impressionist_count %></p>
                  <% unless novel.parent_id != novel.grandparent_id && novel.fin != 0 %>
                    <p class=" icon-float mr-2"><i class="fas fa-pen-nib icon"></i><%= nextcount(novel) %></p>
                  <% end %>
                  <p class="count icon-float mr-2"><i class="fas fa-comment icon"></i><%= novel.comments.count %></p>
                  <p class="count icon-float mr-3"><i class="fas fa-heart icon"></i><%= novel.favorites.count %></p>
                  <span style="font-size: 15px;"><%= time_ago_in_words(novel.created_at) %>前</span>
                </div>
                <% @comments.each do |c| %>
                  <div class="col-md-12 mt-3 pl-0">
                    <div class="mt-0 aboutback" style="text-align:left; height:100%">
                      <p class="btn-flat-logo active-ranking">おすすめレビュー</p>
                      <a href="<%= user_path(c.user) %>" class="reviewname" style="color: #494949;"><%= c.user.name %></a>
                      <p class="pre-wrap" style="color: gray;"><%= c.content %></p>
                      <p style="font-size:13px; color:gray;"><%= c.created_at.strftime('%Y年%m月%d日 %H:%M') %></p> 
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          </a>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/novels/ranking.html.erb
<div class="toppage-box">
  <img src="<%= asset_path "1.jpg" %>" style="width:100%;">
  <div class="top-exp" style="height:100%">
    <h1 class="text-center mt-3">RelayNovel</h1>
    <p class="text-center" style="font-weight:bold;">イチから無限のストーリーが生まれる場所</p>
    <% unless current_user.present? %>
      <a href="novels/new" class="btn mt-0 mb-3">
        <p>アカウント登録 / ログインして</p>
        <p class="button-font">ストーリーを書く</p>
      </a>
    <% end %>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="side col-md-3">
      <h2 style="color: #494949">RelayNovelについて</h2>
      <a href="<%= novels_about_path %>" class="mb-1 display index-search <%= 'active-tag' if current_page?(novels_about_path) %>"><i class="fas fa-desktop icon"></i>サイト紹介</a>
      <a href="<%= novels_qanda_path %>" class="mb-1 display index-search <%= 'active-tag' if current_page?(novels_qanda_path) %>"><i class="far fa-comments icon"></i>Q & A</a>
      <% if current_user.present? %>
        <a href="<%= form_path %>" class="mb-1 display index-search <%= 'active-tag' if current_page?(form_path) %>"><i class="far fa-envelope icon"></i>お問い合わせ</a>
      <% end %>
      <h2 style="color: #494949">ストーリーを探す</h2>
      <a href="<%= root_path %>" class="mb-1 display index-search <%= 'active-tag' if current_page?(root_path) %>"><i class="fas fa-dove icon"></i>完結済みストーリー</a>
      <a href="<%= novels_unfinished_path %>" class="display index-search <%= 'active-tag' if current_page?(novels_unfinished_path) %>"><i class="fas fa-egg icon"></i>未完ストーリー</a>
      <a href="/novels/ranking" class="mt-1 display index-search <%= 'active-tag' if current_page?(novels_ranking_path) %> <%= 'active-tag' if current_page?(novels_ranking_relay_path) %>"><i class="fas fa-crown icon"></i>いいねランキング</a>
      <% if current_user.present? %>
        <a href="<%= novels_following_novels_path %>" class="mt-1 display index-search <%= 'active-tag' if current_page?(novels_following_novels_path) %> <%= 'active-tag' if current_page?(novels_following_relay_path) %>"><i class="fas fa-user-friends icon"></i>タイムライン</a>
      <% end %>
    </div>
  
    <div class="col-md-9">
      <h2 class="toppage-title mb-0" style="color: #494949"><i class="fas fa-crown icon mr-2 pt-2" style="color: #DBB400; font-size:30px;"></i>いいねランキング</h2>
      <div class="mb-3">
        <a href="<%= novels_ranking_path %>" class="btn-flat-logo <%= 'active-ranking' if current_page?(novels_ranking_path) %>">
          <i class="fa fa-chevron-right"></i> オリジナルストーリー
        </a>
        <a href="<%= novels_ranking_relay_path %>" class="btn-flat-logo <%= 'active-ranking' if current_page?(novels_ranking_relay_path) %>">
          <i class="fa fa-chevron-right"></i> リレーストーリー
        </a>
      </div>
      <% @ranking.each do |novel| %>
        <% rand = Rails.env.production? ? "RANDOM()" : "rand()" %>
        <% @comments = novel.comments.order(rand).limit(1) %>
        <% if novel.id == novel.parent_id %>
          <a href="<%= novel_path(novel) %>" class="linkbox">
            <div class="novel-border media-body show">
              <% @order += 1 %>
              <div class="ranking-number mb-2">
                <p style="margin-bottom:0; font-weight:bold; color:#494949;">
                  <% if @order == 1 %>
                    <i class="fas fa-crown icon" style="color: #DBB400;"></i><%= @order %>位
                  <% elsif @order == 2 %>
                    <i class="fas fa-crown icon" style="color: #C9CACA;"></i><%= @order %>位
                  <% elsif @order == 3 %>
                    <i class="fas fa-crown icon" style="color: #C08D5E;"></i><%= @order %>位
                  <% else %>
                    <%= @order %>位
                  <% end %>
                </p>
              </div>
              <p class='font-weight-bold pre-wrap font mr-3' style='font-size:20px;'><%= novel.outline.truncate(100) %></p>
              <div class="form-color">
                <p class="display title" style="color: #494949;">『<%= novel.title %>』</p>
                <object><p class="display" style="color: #494949;">著者：<%= link_to novel.user.name, user_path(novel.user), class:'text-reset' %></p></object>
                <div class="pv-fav-foot-time mt-2">
                  <p class=" icon-float mr-2"><i class="fas fa-shoe-prints icon"></i><%=  novel.impressionist_count %></p>
                  <% unless novel.parent_id != novel.grandparent_id && novel.fin != 0 %>
                    <p class=" icon-float mr-2"><i class="fas fa-pen-nib icon"></i><%= nextcount(novel) %></p>
                  <% end %>
                  <p class="count icon-float mr-2"><i class="fas fa-comment icon"></i><%= novel.comments.count %></p>
                  <p class="count icon-float mr-3"><i class="fas fa-heart icon"></i><%= novel.favorites.count %></p>
                  <span style="font-size: 15px;"><%= time_ago_in_words(novel.created_at) %>前</span>
                </div>
                <% @comments.each do |c| %>
                  <div class="col-md-12 mt-3 pl-0">
                    <div class="mt-0 aboutback" style="text-align:left; height:100%">
                      <p class="btn-flat-logo active-ranking">おすすめレビュー</p>
                      <a href="<%= user_path(c.user) %>" class="reviewname" style="color: #494949"><%= c.user.name %></a>
                      <p class="pre-wrap" style="color: gray;"><%= c.content %></p>
                      <p style="font-size:13px; color:gray;"><%= c.created_at.strftime('%Y年%m月%d日 %H:%M') %></p> 
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          </a>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/novels/unfinished.html.erb
<div class="toppage-box">
  <img src="<%= asset_path "1.jpg" %>" style="width:100%;">
  <div class="top-exp" style="height:100%">
    <h1 class="text-center mt-3">RelayNovel</h1>
    <p class="text-center" style="font-weight:bold;">イチから無限のストーリーが生まれる場所</p>
    <% unless current_user.present? %>
      <a href="novels/new" class="btn mt-0 mb-3">
        <p>アカウント登録 / ログインして</p>
        <p class="button-font">ストーリーを書く</p>
      </a>
    <% end %>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="side col-md-3">
      <h2 style="color: #494949">RelayNovelについて</h2>
      <a href="<%= novels_about_path %>" class="mb-1 display index-search <%= 'active-tag' if current_page?(novels_about_path) %>"><i class="fas fa-desktop icon"></i>サイト紹介</a>
      <a href="<%= novels_qanda_path %>" class="mb-1 display index-search <%= 'active-tag' if current_page?(novels_qanda_path) %>"><i class="far fa-comments icon"></i>Q & A</a>
      <% if current_user.present? %>
        <a href="<%= form_path %>" class="mb-1 display index-search <%= 'active-tag' if current_page?(form_path) %>"><i class="far fa-envelope icon"></i>お問い合わせ</a>
      <% end %>
      <h2 style="color: #494949">ストーリーを探す</h2>
      <a href="<%= root_path %>" class="mb-1 display index-search <%= 'active-tag' if current_page?(novels_path) %>"><i class="fas fa-dove icon"></i>完結済みストーリー</a>
      <a href="<%= novels_unfinished_path %>" class="display index-search <%= 'active-tag' if current_page?(novels_unfinished_path) %>"><i class="fas fa-egg icon"></i>未完ストーリー</a>
      <a href="<%= novels_ranking_path %>" class="mt-1 display index-search <%= 'active-tag' if current_page?(novels_ranking_path) %> <%= 'active-tag' if current_page?(novels_ranking_relay_path) %>"><i class="fas fa-crown icon"></i>いいねランキング</a>
      <% if current_user.present? %>
        <a href="<%= novels_following_novels_path %>" class="mt-1 display index-search <%= 'active-tag' if current_page?(novels_following_novels_path) %> <%= 'active-tag' if current_page?(novels_following_relay_path) %>"><i class="fas fa-user-friends icon"></i>タイムライン</a>
      <% end %>
    </div>
  
    <div class="col-md-9">
      <h2 class="toppage-title mb-0" style="color: #494949"><i class="fas fa-egg icon mr-2 pt-2" style="color: #5fde7c; font-size:30px;"></i>未完ストーリー</h2>
      <% @novels.each do |novel| %>
        <% rand = Rails.env.production? ? "RANDOM()" : "rand()" %>
        <% @comments = novel.comments.order(rand).limit(1) %>
        <% if novel.parent_id == novel.grandparent_id && novel.fin == 0 && novel.id == novel.parent_id %>
          <a href="<%= novel_path(novel) %>" class="linkbox">
            <div class="novel-border media-body show">
              <p class='font-weight-bold pre-wrap font mr-3' style='font-size:20px;'><%= novel.outline.truncate(100) %></p>
              <div class="form-color">
                <p class="display title" style="color: #494949;">『<%= novel.title %>』</p>
                <object><p class="display" style="color: #494949;">著者：<%= link_to novel.user.name, user_path(novel.user), class:'text-reset' %></p></object>
                <div class="pv-fav-foot-time mt-2">
                  <p class=" icon-float mr-2"><i class="fas fa-shoe-prints icon"></i><%=  novel.impressionist_count %></p>
                  <% unless novel.parent_id != novel.grandparent_id && novel.fin != 0 %>
                    <p class=" icon-float mr-2"><i class="fas fa-pen-nib icon"></i><%= nextcount(novel) %></p>
                  <% end %>
                  <p class="count icon-float mr-2"><i class="fas fa-comment icon"></i><%= novel.comments.count %></p>
                  <p class="count icon-float mr-3"><i class="fas fa-heart icon"></i><%= novel.favorites.count %></p>
                  <span style="font-size: 15px;"><%= time_ago_in_words(novel.created_at) %>前</span>
                </div>
                <% @comments.each do |c| %>
                  <div class="col-md-12 mt-3 pl-0">
                    <div class="mt-0 aboutback" style="text-align:left; height:100%">
                      <p class="btn-flat-logo active-ranking">おすすめレビュー</p>
                      <a href="<%= user_path(c.user) %>" class="reviewname" style="color: #494949"><%= c.user.name %></a>
                      <p class="pre-wrap" style="color: gray;"><%= c.content %></p>
                      <p style="font-size:13px; color:gray;"><%= c.created_at.strftime('%Y年%m月%d日 %H:%M') %></p> 
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          </a>
        <% end %>
      <% end %>
    </div>
  </div>
</div>