config/routes.rb
Rails.application.routes.draw do
 
 root to: 'novels#index'
 
 get 'login', to: 'sessions#new'
 post 'login', to: 'sessions#create'
 delete 'logout', to: 'sessions#destroy'
 
 get 'form', to: 'users#form'
 get 'signup', to: 'users#new'
 resources :users do
    member do
      get :relaied
      get :followings
      get :followers
      get :likes
    end
  end
 
 get 'novels/unfinished', to: 'novels#unfinished'
 get 'novels/ranking', to: 'novels#ranking'
 get 'novels/following_novels', to: 'novels#following_novels'
 get 'novels/about', to: 'novels#about'
 get 'novels/qanda', to: 'novels#qanda'
 get 'novels/guideline', to: 'novels#guideline'
 get 'novels/rule', to: 'novels#rule'
 get 'novels/privacy', to: 'novels#privacy'
 get 'novels/ranking_relay', to: 'novels#ranking_relay'
 get 'novels/following_relay', to: 'novels#following_relay'
 resources :novels do
  member do
    get :continue
    get :last
  end
  resources :comments, only: [:create, :destroy]
 end
 
 resources :relationships, only: [:create, :destroy]
 resources :favorites, only: [:create, :destroy]
 resources :notifications, only: :index
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4 fixed-top">
  <nav class="navbar navbar-expand-sm">
    <a class="navbar-brand nav-links font-weight-bold" style="font-size:20px;" href="/">RelayNovel<span class="ml-2">リレー小説投稿サイト</span></a>
    
    <!--<div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">-->
      <ul class="navbar-nav" style="margin:0 0 0 auto;">
        <% if logged_in? %>
          <div class="dropdown shadow-none" style="display:inline-block;">
            <button type="button" class="btn dropdown-toggle font-weight-bold" id="dropdownMenuButton" style='transition:0.5s;' data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">メニュー</button>
            <div class="dropdown-menu dropdown-menu-right shadow-none" style="background-color:white;" aria-labelledby="dropdownMenuButton">
              <a class="dropdown-item font-weight-bold" style="color:gray;" href="<%= user_path(current_user) %>">マイページ</a>
              <a class="dropdown-item font-weight-bold" style="color:gray;" href="<%= new_novel_path %>">新規ストーリー作成</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item font-weight-bold" style="color:gray;" href="<%= novels_about_path %>">サイト紹介</a>
              <a class="dropdown-item font-weight-bold" style="color:gray;" href="<%= novels_qanda_path %>">Q & A</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item font-weight-bold" style="color:gray;" href="<%= novels_rule_path %>">利用規約</a>
              <a class="dropdown-item font-weight-bold" style="color:gray;" href="<%= novels_guideline_path %>">ガイドライン</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item font-weight-bold" style="color:gray;" href="<%= logout_path %>" data-method="delete">ログアウト</a>
            </div>
          </div>
        <% else %>
          <li class="nav-item res"><%= link_to 'アカウント登録', signup_path, class: 'nav-links mr-3 font-weight-bold', style:'transition:0.5s;' %></li>
          <li class="nav-item res"><%= link_to 'ログイン', login_path, class: 'nav-links font-weight-bold', style:'transition:0.5s;' %></li>
          <div class="dropdown shadow-none submenue">
            <button type="button" class="btn dropdown-toggle font-weight-bold" id="dropdownMenuButton" style='transition:0.5s;' data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">メニュー</button>
            <div class="dropdown-menu dropdown-menu-right shadow-none" style="background-color:white;" aria-labelledby="dropdownMenuButton">
              <a class="dropdown-item font-weight-bold" style="color:gray;" href="<%= signup_path %>">アカウント登録</a>
              <a class="dropdown-item font-weight-bold" style="color:gray;" href="<%= login_path %>">ログイン</a>
            </div>
          </div>
        <% end %>
      </ul>
    <!--</div>-->
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>RelayNovel</title>
    <%= favicon_link_tag('favicon.ico') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="./assets/stylesheets/application.css">
    <link rel="stylesheet" href="./assets/stylesheets/novels.scss">
    <link rel="stylesheet" href="./assets/stylesheets/sessions.scss">
    <link rel="stylesheet" href="./assets/stylesheets/users.scss">
    
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
     
  </head>

  <body style="background-color:rgba(255,255,240,0.3);">
    <%= render 'layouts/navbar' %>
    
    <div class="container main">
      <%= render 'layouts/flash_messages' %>
      <%= yield %>
    </div>

    <footer class="mt-5">
      <div>
        <p class="mt-2 ml-2"><small>&copy; 2020 RelayNovel</small></p>
      </div>
    </footer>
  </body>
</html>